# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - P2Trippi-Website

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
env:
  WORKING_DIRECTORY: ./TrippiFrontend


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
        working-directory: ${{env.WORKING_DIRECTORY}}
        
      - name: Tar Files
        run: zip -r my_files.zip ./TrippiFrontend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./my_files.tar


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'P2Trippi-Website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FE07FF51B6CF42B6ADBB19D00065E110 }}
          package: .
