# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - P2Trippi-Website

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  WORKING_DIRECTORY: ./TrippiFrontend
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - name: Install dependencies
        run: npm ci
        working-directory: ${{env.WORKING_DIRECTORY}}
      
      - name: Build
        run: npm run build:ci
        working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Test
        run: npm run test:ci
        working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'P2Trippi-Website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2E77DA36CD2145148DFBA33549D9E228 }}
          package: .
